# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

slug: amna-template-fargate-deployment
name: "[FARGATE][1] Deployment"
description: |
  Semi-automatically generates Terraform configuration and deploys the application to AWS Fargate. 
  Requires the data from "[FARGATE][0] Containerize the Application" workflow execution or an application with Dockerfile to work with.
  
  IMPORTANT: terraform_apply step requires manual confirmation, please, carefully review the suggested deployment plan before accepting it.
  This stage will execute "terraform apply" command using provided AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY credentials.
  Terraform configuration to be applied is stored under <project_root>/airun/terraform directory.
  
  Workflow requires filesystem, filesystem_ext and cli-mcp-server Plugin integrations, AWS integration (it is recommended to use read-only credentials),
    nhrun and nhcheck scripts to be available in the $PATH
    and terraform, aws cli and docker to be available on your machine.
  
  Prerequisites:
   1. Workflow requires bash on your local machine to run properly.
   2. Workflow uses <project_root>/airun directory as an output directory, make sure this directory is empty before run.
   3. terraform, aws cli and docker should be installed on the local machine.
   4. Add nhrun and nhcheck scripts (requires bash to run) in /usr/local/bin or similar directory from the $PATH environment variable.
   5. Set Plugin and AWS integrations.
   6. Run plugins and give them access to the project tree:
    - Set environment variables pointing to root of your project: ALLOWED_DIR, FILE_PATHS
    - Set environment variables pointing to project_root/airun directory: PROJECT_BOOTSTRAP
    - Set environment variables with AWS account credentials (for Terraform deployment) AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
    - Run plugin: codemie-plugins mcp run -s filesystem -e filesystem=FILE_PATHS
    - Run plugin: codemie-plugins mcp run -s filesystem_ext -e filesystem_ext=ALLOWED_DIR,PROJECT_BOOTSTRAP
    - Run plugin: codemie-plugins mcp run -s cli-mcp-server -e cli-mcp-server=ALLOWED_DIR,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
mode: Sequential
execution_config:
  assistants:
    - id: aws_terraform_expert
      exclude_extra_context_tools: true
      system_prompt: |
        You are an expert DevOps engineer experienced in configuring AWS resources, with the strong knowledge of Terraform.
        You have an access to local project and ability to run tools.
        You are also allowed to use AWS tool to view aws resources. Avoid using example resources or names, use actual resources instead.
  
        IMPORTANT:
        You are not allowed to modify any of the project files under any circumstances.
        The only files you can edit are under airun directory.
        If there is no airun directory, create one under the root of a project.
        *You ARE NOT allowed to modify or create any of AWS resources, the only thing you can do is observe.*
      tools:
        - name: _read_file
        - name: _read_multiple_files
        - name: _write_file
        - name: _edit_file
        - name: _create_directory
        - name: _list_directory
        - name: _directory_tree
        - name: _move_file
        - name: _search_files
        - name: _get_file_info
        - name: _list_allowed_directories
        - name: _append_structured_file
        - name: _search_files_by_regex
        - name: _read_file_lines
        - name: AWS

    - id: command_runner
      exclude_extra_context_tools: true
      system_prompt: |
        You are an assistant designed to execute command line tools.
      tools:
        - name: _append_structured_file
        - name: _move_file
        - name: _list_directory
        - name: _directory_tree
        - name: _list_allowed_directories
        - name: _run_command
        - name: _show_security_rules

  enable_summarization_node: false
  max_concurrency: 1

  states:
    - id: generate_fargate_terraform
      assistant_id: aws_terraform_expert
      task: |
        You are given the task to generate Terraform configuration for the application's AWS Fargate deployment.
        You are allowed to use AWS integration to acquire all necessary information about the account.
  
        Follow these steps to accomplish the task:
        1. Read existing terraform configuration stored at <project_base>/airun/terraform.
        2. Analyse the project and identify it properties.
        3. Identify available aws regions and availability zones, use only one of each.
        4. Update Terraform configuration with application deployment with AWS Fargate.
        5. Read all of the Terraform files and verify your solution:
          - Ensure all there are no missing essential resources.
          - Check there are no resource duplicates.
          - Ensure no deprecated arguments used.
          - Ensure all terraform variables are set, there should be no variable without a value
  
        IMPORTANT:
        Do not create any non-configuration files (Do not include README or similar files).
        Keep file structure clean. Use one file for one resource type.
        *You ARE NOT allowed to modify or create any of AWS resources, the only thing you can do is to observe.*
        You are not allowed to create / modify / delete any file outside of the <project_base>/airun/terraform directory.
      next:
        state_id: update_env_vars

    - id: update_env_vars
      assistant_id: aws_terraform_expert
      task: |
        You are given the task to analyse the application, identify configurable environment variables
        and update the Terraform configration with them.
        You are allowed to use AWS integration to acquire all necessary information about the account.
  
        Follow these steps to accomplish the task:
        1. Carefully analyse the project and Dockerfile, and identify which environment variables can be used to configure it.
        2. Read existing Terraform configuration stored at <project_base>/airun/terraform.
        3. Identify which environment variables are missing in the Terraform configuration.
        4. Update Terraform configuration with those variables, using the most suitable values for them.
        5. Read all of the Terraform files and verify your solution:
          - Ensure all there are no missing values.
          - Check there are no duplicates.
          - Ensure that values of variables are suitable for AWS deployment and won't broke the application.
  
        IMPORTANT:
        Do not create any non-configuration files (Do not include README or similar files).
        Keep file structure clean. Use one file for one resource type.
        *You ARE NOT allowed to modify or create any of AWS resources, the only thing you can do is to observe.*
        You are not allowed to create / modify / delete any file outside of the <project_base>/airun/terraform directory.
      next:
        state_id: push_to_ecr

    - id: push_to_ecr
      assistant_id: command_runner
      task: |
        You are given the task to push images, used in Terraform configuration to ECR.
        
        Follow the steps to accomplish this task:
        1. Identify an ECR image name (ECR_IMAGE_NAME) using Terraform configuration and aws cli tools.
        2. Update Terraform configuration with ECR_IMAGE_NAME.
        3. Docker login to ECR.
        4. Build Docker image, make sure to build image compatible with Fargate architecture (use "--platform linux/amd64" flag), use ```nhrun <command to build ECR_IMAGE_NAME>``` command.
        5. Using the output of the previous command identify PID_FILENAME and LOG_FILENAME.
        6. Execute ```nhcheck <PID_FILENAME>``` to identify if the process is already finished. Retry this step if not. Do not try using other commands when timed out it is expected to happen.
        7. Review the last 100 lines of LOG_FILENAME.
        8. If built has failed, fix issues and start over from step 4
        9. Push ECR_IMAGE_NAME image to ECR
        
        IMPORTANT:
        You are not allowed to create any new files.
        You are not allowed to create new AWS resources, use AWS tools only to observe an account information.
      next:
        state_id: terraform_plan

    - id: terraform_plan
      assistant_id: command_runner
      task: |
        You are given the task to run and observe terraform plan output.
        
        Steps to follow:
        1. Change working directory to airun/terraform.
        2. Execute "terraform init" command using tools within airun directory. 
        3. Execute "terraform plan -no-color" command using tools within airun directory, skip this step if terraform init command failed.
        4. Respond with a valid JSON.
        
        Output schema:
        {
          "success": "Boolean true | false. If terraform plan command executed without errors return true, otherwise false",
          "log": "Exactly the output of the command execution log without ANY modifications, use empty string in case of success."
        }
        
        IMPORTANT:
        Do not try to fix any issues appeared while running terraform commands.
        *You MUST provide a valid JSON output only, without any decoration and thoughts.*
      output_schema: |
        {
          "success": "Boolean true | false. If terraform plan command executed without errors return true, otherwise false",
          "log": "Exactly the output of the command execution log without ANY modifications, use empty string in case of success."
        }
      next:
        condition:
          expression: success == True
          then: terraform_apply
          otherwise: terraform_fixer

    - id: terraform_apply
      assistant_id: command_runner
      wait_for_user_confirmation: true
      task: |
        You are given the task to run and observe terraform apply output.
    
        Follow these steps to accomplish the task:
        1. Change working directory to airun/terraform.
        2. Execute ```nhrun terraform apply -no-color -auto-approve``` command using _run_command tool.
        3. Using output of the previous command identify PID_FILENAME and LOG_FILENAME from it's output.
        4. Execute ```nhcheck <PID_FILENAME>``` to identify if the process is already finished. Retry this step if not. Do not try using other commands when timed out it is expected to happen.
        5. Read LOG_FILENAME when process finishes.
        6. Analyse log file and identify if there were any errors.
        7. Respond with a valid JSON.
        
        Output format:
        {
          "success": "Boolean true | false. If process finished without any errors return true, otherwise false",
          "log": "Exactly the output of the command execution log without ANY modifications, use empty string in case of success."
        }
        
        IMPORTANT:
        Do not try to fix any issues appeared in log file.
        You should not produce any user-readable output as the user is unlikely to monitor your actions in real-time.
        *You MUST provide a valid JSON output only, without any decoration and thoughts.*
      output_schema: |
        {
          "success": "Boolean true | false. If process finished without any errors return true, otherwise false",
          "log": "Exactly the output of the command execution log without ANY modifications, use empty string in case of success."
        }
      next:
        condition:
          expression: success == True
          then: end
          otherwise: terraform_fixer

    - id: terraform_fixer
      assistant_id: aws_terraform_expert
      task: |
        You are given the task to fix issues appeared while running the Terraform.
        Terraform configuration is stored under the <project_base>/airun/terraform directory.
        Analyse provided log and implement changes to address found errors.
  
        IMPORTANT:
        You are not allowed to create new directories or any non terraform files.
        Implement changes without new files creation if possible.
        Do not create temporary files, modify existing terraform configuration instead.
      next:
        keep_history: false
        state_id: terraform_plan
