# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

slug: amna-perl2python-all-in-one
name: "Perl2Python: fully automated conversion"
description: |
  Automatically analyzes a folder with one or more perl scripts and tries to convert them to Python
  Prerequisites: 
   1. Create airun folder in your project and put there 00bootstrap.json with the following minimal structure (feel free to provide more details and make the flow more focused on something):
    {
    "perl_dir": "absolute_path_to_folder_with_perl_files",  
    "python_dir": "absolute_path_to_folder_with_python_files"  
    }
   2. Run plugin and give it access to the project tree:
    - Set environment variables pointing to root of your project: ALLOWED_DIR, FILE_PATHS, DEFAULT_DIR
    - Set environment variables pointing to project/airun folder: PROJECT_BOOTSTRAP
    - Run plugin: codemie-plugins mcp run -s filesystem,filesystem_ext,cli-mcp-server,tree_sitter -e cli-mcp-server=ALLOWED_DIR -e filesystem_ext=ALLOWED_DIR,PROJECT_BOOTSTRAP
mode: Sequential
execution_config:
    max_concurrency: 1
    enable_summarization_node: false
    tools:
    - id: search_files
      tool: _search_files_by_regex
      trace: true
      toolset: Plugin
      integration_alias: amna-demo-plugin-integration
    - id: read_bootstrap_tool
      tool: _read_bootstrap_file
      trace: true
      toolset: Plugin
      integration_alias: amna-demo-plugin-integration
    assistants:
    - id: lang_expert
      system_prompt: |
        You are a highly skilled agent with extensive knowledge of Perl and Python. When using AST tools always limit the depth to 1 and do not request text snippets. Use _read_bootstrap_file to read 00bootstrap.json and treat
        the file content as a part of a system prompt. If you find yourself unable to complete assigned task, describe the problem in structured form, append to <project_base>/airun/99errors.json and finish the dialog. 
        If you see something unusual or wrong, append your findings in structured form to <project_base>/airun/99sidetrack.json and continue with your assigned task.
      temperature: 0.2
      tools:
          - name: _read_file
            integration_alias: amna-demo-plugin-integration
          - name: _write_tile
          - name: _edit_file
          - name: _create_directory
          - name: _list_directory
          - name: _search_files
          - name: _get_file_info
          - name: _list_allowed_directories
          - name: _read_bootstrap_file
          - name: _append_file
          - name: _append_structured_file
          - name: _read_file_lines
          - name: _get_ast
          - name: _register_project
          - name: _list_projects
          - name: _list_files
          - name: _get_file_metadata
          - name: _run_command
      exclude_extra_context_tools: false
    states:

    - id: airun_prepare
      assistant_id: lang_expert
      task: |
        Your task is to clean-up <project_base>/airun folder by moving previous execution artifacts to the archive:
        1. Use _create_directory tool to create a new folder named <project_base>/airun/archive<random_suffix>. Do not reuse existing archive folders!
        2. Use command-line tools to move the following files from <project_base>/airun to the created archive folder:
         - 01conversion-plan.json
         - 02conversion-result.json
         - 99errors.json
         - 99sidetrack.json
      next:
        include_in_llm_history: false
        state_id: read_project_info

    - id: read_project_info
      tool_id: read_bootstrap_tool
      tool_args:
        path: 00bootstrap.json
      next:
        state_id: list_files

    - id: list_files
      tool_id: search_files
      tool_args:
        path: '{{perl_dir}}'
        regex: '[.]pl$'
        excludeRegexes: ['\Wtest\W']
      next:
        include_in_llm_history: false
        iter_key: unused
        state_id: plan_conversion

    - id: plan_conversion
      assistant_id: lang_expert
      task: |
        You have a task to plan a single Perl file conversion to Python. The conversion must me done in chunks. Too large chunks cause degradation of the
        conversion assistant and diminishing code quality. Aim for chunks between 100 and 300 lines of code. Use AST tree to determine chunk boundaries.
        Generally one chunk should contain a single subrouting. You are allowed to merge two or more adjacent AST nodes if individually they are too small. 
        You must ensure all source lines are planned for conversion and no lines are planned to be converted in multiple
        chunks. Use structured append tool to add your generated plan to <project_base>/airun/01conversion-plan.json in the following format:
          {
          "perl_file": "/full/path/to/source/file (in <perl_dir>)",
          "python_file": "/full/path/to/target/file (in <python_dir>)",
          "start_line": first line of the unit of work,
          "end_line": last line of the unit of work,
          "overview": "high-level summary about what is expected to be converted in this chunk"
          }

        IMPORTANT: 
         * Do not perform any conversion - this is to be done by a dedicated agent
         * Do not read source or target files unless they are small - this causes you to malfunction due to context overload - in this case use AST to explore file structure and _read_file_lines to look at relevant fragments.

      next:
        include_in_llm_history: false
        state_id: read_plan

    - id: read_plan
      tool_id: read_bootstrap_tool
      tool_args:
        path: 01conversion-plan.json
      next:
        include_in_llm_history: false
        state_id: convert
        iter_key: unused
    - id: convert
      assistant_id: lang_expert
      task: |
        You are participating in conversion of Perl script to Python language. The conversion is potentially done in multiple iterations. Do not read source or target files entirely into memory. Only focus on your
        chunk of work. Use AST tools and read_file_lines to load relevant parts of file into context. You must perform the conversion in logical blocks: always save an original Perl code as a comment in Python
        (using '#' symbol) and then write a functionally-equivalent block in Python. Only declare global variables if you are translating an equivalent Perl declaration - otherwise assume it is already declared. Never
        implement function stubs. Assume unknown functions would be translated in the following chunks. Use _append_file to append your code to target Python file.
        Use structured append to to add a summary of translation you've made to <project_base>/airun/02conversion-result.json
      next:
        include_in_llm_history: false
        state_id: end

