# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

slug: amna-serverless-02-api-gateway
name: "[SERVERLESS][2] API Gateway Generation"
description: |
  Automatically generates Terraform configuration for AWS API Gateway for generated lambdas.
  Requires data from "[SERVERLESS][1] Lambda Writer" workflow execution.

  This workflow is a part of the split "[SERVERLESS] Automated Monolith to Serverless Migration" workflow.
mode: Sequential
execution_config:
  enable_summarization_node: false
  max_concurrency: 1

  assistants:
    - id: aws_terraform_expert
      exclude_extra_context_tools: true
      system_prompt: |
        You are an expert DevOps engineer experienced in configuring AWS resources, with the strong knowledge of Terraform.
        You have an access to local project and ability to run tools.
        You are also allowed to use AWS tool to view aws resources. Avoid using example resources or names, use actual resources instead.

        IMPORTANT:
        You are not allowed to modify any of the project files under any circumstances.
        The only files you can edit are under airun directory.
        If there is no airun directory, create one under the root of a project.
        *You ARE NOT allowed to modify or create any of AWS resources, the only thing you can do is observe.*
      tools:
        - name: _read_file
        - name: _read_multiple_files
        - name: _write_file
        - name: _edit_file
        - name: _create_directory
        - name: _list_directory
        - name: _directory_tree
        - name: _move_file
        - name: _search_files
        - name: _get_file_info
        - name: _list_allowed_directories
        - name: _append_structured_file
        - name: _search_files_by_regex
        - name: _read_file_lines
        - name: AWS

  tools:
    - id: read_bootstrap_tool
      tool: _read_bootstrap_file
      toolset: Plugin
      trace: true

  states:
    - id: read_lambdas_info
      tool_id: read_bootstrap_tool
      tool_args:
        path: lambdas/lambda_info.json
      next:
        state_id: api_gateway_config_generator
        iter_key: _

    - id: api_gateway_config_generator
      assistant_id: aws_terraform_expert
      task: |
        You are given the task to update Terraform configuration files using tools with an api-gateway configuration for the provided lambda.
        You are also allowed to use AWS tool to view aws resources. Avoid using example resources or names, use actual resources instead.

        Follow these steps to accomplish the task:
        1. Read existing terraform configuration stored at <project_base>/airun/terraform.
        2. Read required to be added lambda.
        3. Identify available aws regions and availability zones, use only one of each.
        4. Update Terraform configuration for api-gateway, ensuring all lambda endpoints are added.
        5. Read all of the terraform files and verify your solution:
          - Ensure all resources used in api-gateway are present in Terraform configuration.
          - Check there are no resource duplicates.
          - Ensure no deprecated arguments used.

        IMPORTANT:
        Do not include anything besides api-gateway configuration, other parts will be added by different agent.
        Do not create any non-configuration files (Do not include README).
        Keep file structure clean. Use one file for one resource type.
        *You ARE NOT allowed to modify or create any of AWS resources, the only thing you can do is to observe.*
        You are not allowed to create / modify / delete any file outside of the <project_base>/airun/terraform directory.
      next:
        state_id: end