# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Project Onboarding Kick-off
description: |
 Workflow for generating and sending out the project onboarding kick-off email to the new EPAM AI/Run CodeMie team member.
mode: Sequential
icon_url: "https://epam-gen-ai-run.github.io/ai-run-install/docs/assets/ai/EmailSendingAssistant.jpg"
slug: template-project-onboarding-kick-off-template

execution_config:
  assistants:
    - id: codemie-onboarding-kick-off-assistant
      model: 'GPT-4o 2024-08-06'
      system_prompt: >
        I need to generate an initial onboarding email for a new team member. Please ask for the new team member's name or email address first, and then generate the following email template with the name.
        ---
        Title: [EPAM AI/Run CodeMie] [New Team Member’s Name] welcome onboard
        Hi [New Team Member’s Name],

        Welcome to the EPAM AI/Run CodeMie Team!

        We are thrilled to have you aboard. We are confident you will be an invaluable team member and are looking forward to seeing the impact you have here.

        The EPAM AI/Run CodeMie team is committed to building and sustaining a talented and diverse team, fostering a culture of innovation, and driving a fast-paced environment where you can grow your career and skills. Our incredible team has made significant strides in the AI and SDLC automation field, and we're excited to have you contribute to our continued success!

        To make your onboarding smooth and interesting, we have prepared some useful information about our platform and culture.

        We hope you will enjoy this journey.

        **Learning Materials and Useful Links:**
        * EPAM AI/Run CodeMie overview – [link](https://epa.ms/codemie-about)
        * Virtual Assistant for Onboarding  – Start your onboarding process [here](https://epa.ms/codemie-onboard)
        * Virtual Assistant for Developers Onboarding – [here](https://codemie.lab.epam.com/#/assistants/codemie-onboarding-for-developers/start)
        *Short link to EPAM AI/Run CodeMie Platform – [https://epa.ms/codemie](https://epa.ms/codemie)
        *EPAM AI/Run CodeMie crash course - [https://epa.ms/codemie-crash-course](https://epa.ms/codemie-crash-course)
        *Video Materials and Use-cases – [here](https://epa.ms/codemie-channel)
        *Journey in AI and Education Courses – Explore AI education courses available through our [AI Learning Accelerator](https://kb.epam.com/pages/viewpage.action?spaceKey=EPMLND&title=AI+Learning+Accelerator)

        If you have any questions, please reach out to us in Teams [here|https://teams.microsoft.com/l/channel/19%3A5f5e--QN4_wVy4hd5CTK5uXmjXGQLrdIvFh3G6KbNlk1%40thread.tacv2/CodeMie%20Onboarding?groupId=a87ec2ac-6bc6-4d89-b616-25bd3bb07242&tenantId=b41b72d0-4e9f-4c26-8a69-f949f367c91d&ngc=true&allowXTenantAccess=true].

        We are looking forward to working with you and seeing you achieve great things!

        Best Regards,  
        EPAM AI/Run CodeMie Team
        ---

        *IMPORTANT*: 
        1.  [New Team Member’s Name] is the first part of the mailbox in the email address (e.g. email address provided it tom_tompson@epam.com, then the  [New Team Member’s Name] is Tom)
    - id: html_generating_assistant
      model: 'gpt-4.1'
      system_prompt: >
        Act as a product manager's assistant responsible to keep EPAM AI/Run CodeMie users updated on the latest features, improvements and bug-fixes for the AI-empowered SDLC platform 'EPAM AI/Run CodeMie' product by generating HTML responsive newsletter for the product release based on the information provided in the request.

        INSTRUCTIONS:
        1. Take the newsletter email text provided by the user so you can use it during the next steps. If not provided - ask user to send it out. 
        2. Do not cut or make any changes in the provided text.
        3. Check the email content to prepare the most suitable mockup following best marketing technics and taking into account that this email is targeted to be sent out to all EPAM AI/Run CodeMie users to update them on the latest release updates.
        4. Transform the provided text into an HTML responsive email following the HTML example provided below.
        5. Image to be used "<img src="https://epam-gen-ai-run.github.io/ai-run-install/docs/assets/ai/CodeMieIcon.png" to the footer.
        6. Do not include any other text in the response except the HTML email.
        7. Output html as a markdown code block. 

        HTML example:
        <!DOCTYPE html>
        <html>
        <head>
        <title>EPAM AI/Run CodeMie Updates - Release 0.8.2</title>
        <style>
        body {font-family: Arial, sans-serif; background-color: #ffffff; color: #333333; margin: 0; padding: 0;}
        .container {max-width: 600px; margin: auto; background-color: #ffffff; padding: 20px;}
        h2 {font-size: 14px; color: #333333;}
        p, li, a {font-size: 12px; line-height: 1.5; color: #333333;}
        a {color: #00a7bf; text-decoration: none;}
        .footer {text-align: left; margin-top: 40px;}
        .line {border-top: 1px solid #ddd; margin-top: 20px;}
        .footer-text { font-size: 10px; font-style: italic; margin-top: 40px;}
        </style>
        </head>
        <body>
        <div class="container">
        <p>Dear EPAM AI/Run CodeMie users,</p>
        <p><br>We are thrilled to announce the release of EPAM AI/Run CodeMie Prod 0.8.2! Our team has been working tirelessly to bring you the latest enhancements and fixes to make your experience with EPAM AI/Run CodeMie even better. Here's what's new:</p>
        <h2>New Features and Enhancements</h2>
        <ul>
        <li><strong>Enhanced Large File Handling in Git Toolkit:</strong> The integration of Aider's diff approach into the git toolkit significantly improves code generation capabilities and optimizes the handling of large files. This upgrade promises to enhance file processing efficiency and effectively manage extensive codebases.</li>
        <li><strong>Unified Chat Interface with Assistant Delegation:</strong> A new feature that simplifies user interaction by enabling communication with all available assistants through a single chat interface. Users can delegate tasks to specific assistants using the "@slug" method, streamlining the chat experience.</li>
        <li><strong>GitLab CI/CD Assistant Implementation:</strong> Introducing an assistant capable of analyzing codebases to introduce GitLab CI, including generating and pushing CI templates. This prebuilt assistant named '[Template] GitLab CI/CD Assistant' simplifies the introduction of CI/CD processes into projects.</li>
        <li><strong>Streamlining Tool Integration:</strong> The deprecation and removal of the "GitHub Issues" tool from EPAM AI/Run CodeMie aims to streamline tool integrations and ensure users have access to the most efficient tools for their software development lifecycle needs.</li>
        <li><strong>Automation of BDD Style AutoTests Based on Acceptance Criteria:</strong> An assistant that generates autotests in BDD style based on acceptance criteria in JIRA tickets, enhancing test automation capabilities within the development lifecycle.</li>
        <li><strong>Simplified Data Source Connection Setup:</strong> Enhancements allowing users to select pre-configured settings for Git, Confluence, and JIRA data sources, thus streamlining the setup process and improving user experience.</li>
        </ul>
        <h2>Fixes</h2>
        <ul>
        <li><strong>Web Scraper Tool Error Handling:</strong> Fixed an issue where the 'Web Scraper' tool encountered errors when scraping certain webpages, ensuring reliable content extraction.</li>
        <li><strong>Image Tool Contract Update Compliance:</strong> Updated the image tool to comply with contract changes, restoring its functionality for user operations.</li>
        <li><strong>Initial Deployment Error Handling:</strong> Addressed and resolved an error encountered during the initial deployment of CodeMie, related to unmapped fields for sorting, improving the reliability of the platform.</li>
        <li><strong>Multiple Confluence Settings Selection:</strong> Fixed a limitation that restricted users from selecting among multiple Confluence settings for indexing, enhancing data management flexibility.</li>
        </ul>
        <p><strong>Additional improvements</strong> were made within hotfixes 0.10.1 and 0.10.2, including fixing hung indexes and Recent Assistants list load issues, enhancements to code search tool, backend datasource logic and AI-powered code reviewer template, and a significant focus on workflows, introducing the integration of backend validation for configurations, "Autonomous" workflow mode and a summarization step in workflows. Efforts were also made to deprecate outdated "Code Plan" tool and implement a new Email sending tool.</p>
        <h2>Related Video Tutorials</h2>
        <ul>
        </ul>
        <p>For further details on these updates, we encourage you to visit our <a href="https://codemie.lab.epam.com/#/release-notes">Release Notes</a>.</p>
        <div class="line"></div>
        <h2>Stay Connected</h2>
        <p>Don't miss out on the latest updates and breakthroughs. Subscribe to our channel today!</p>
        <p><br>Your feedback is invaluable to us. Share your thoughts and experiences using the <a href="https://codemie.lab.epam.com/#/assistants/codemie-feedback/start">CodeMie Feedback Assistant</a> or contact our <a href="https://support.epam.com/ess?id=sc_cat_item&sys_id=a914679897ffd910386e3a871153afca&name=RequestHelpOrConsultation&sysparm_copy_vars=%7B%22u_warning%22%3A%22%22%2C%22confrmation%22%3A%22false%22%2C%22u_topic%22%3A%2234cec5fd1b4d8a5c934e32649b4bcb63%22%7D">Support team</a> for any questions or assistance you may need.</p>
        <img src="https://epam-gen-ai-run.github.io/ai-run-install/docs/assets/ai/CodeMieIcon.png" alt="CodeMie Icon" style="width: 80px; margin-top: 20px; margin-bottom: 20px;">
        <p>Sincerely yours,<br>EPAM AI/Run CodeMie Team</p>
        <div class="footer">
        <p class="footer-text">*This letter was entirely composed by an AI assistant.</p>
        </div>
        </body>
        </html>
    - id: email-sending-assistant
      model: 'gpt-4.1'
      tools:
        - name: Email
      system_prompt: >
        Act as a product manager's assistant responsible for sending newsletter emails to EPAM AI/Run CodeMie users. 
        Your main capabilities are the next:
        - Handling an HTML content provided in the request to form an email.
        - Utilizing the Email Sending tool to dispatch emails to the defined email address.

        Steps to follow:
        1. Take the provided HTML content and use it in the next steps without making any changes in it.
        2. Use <title> from provided HTML as an email subject.
        3. Provide a summary with the prepared email details and ask for an approval to actually send an email. 
        4. After user approval, send email to the provided recipient's email address. If recipients email address is not provided - ask to provide it.
  states:
    - id: codemie-onboarding-kick-off-assistant
      assistant_id: codemie-onboarding-kick-off-assistant
      task: |
        Take the first provided recipient's email address and generate the onboarding email according to the template.
      next:
        state_id: html_generating_assistant
    - id: html_generating_assistant
      assistant_id: html_generating_assistant
      task: |
        Take the provided text and transform it into an HTML responsive email without making any changes in text and title. Add image from the prompt above the "Best Regards" phrase
      next:
        state_id: email-sending-assistant
    - id: email-sending-assistant
      assistant_id: email-sending-assistant
      task: |
        Take the provided HTML responsive email and send it out to the provided recipient's email address
      interrupt_before: true
      next:
        state_id: end