# Copyright 2026 EPAM Systems, Inc. ("EPAM")
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import os

from fastapi import FastAPI
from opentelemetry import context as otel_context
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import ReadableSpan, Span, SpanProcessor, TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
from opentelemetry.semconv.resource import ResourceAttributes
from opentelemetry.trace import Tracer

from codemie.configs.config import config


class _DropAsgiSendSpansProcessor(SpanProcessor):
    """Filters out the high-frequency ASGI 'http send' spans generated by
    FastAPIInstrumentor for every chunk of a streaming response.

    These spans (name ending with ' http send', asgi.event.type=http.response.body)
    add no diagnostic value and flood the trace backend for SSE/streaming endpoints.
    All other spans are forwarded to the wrapped inner processor unchanged.
    """

    def __init__(self, inner: SpanProcessor) -> None:
        self._inner = inner

    def on_start(self, span: Span, parent_context: otel_context.Context | None = None) -> None:
        self._inner.on_start(span, parent_context)

    def on_end(self, span: ReadableSpan) -> None:
        if span.name.endswith((" http send", " http receive")):
            return
        # Suppress pool connection-checkout spans generated by OTel's Engine.connect() wrapper
        # for every connection acquired from the pool.  They add no diagnostic value and
        # dominate trace titles in Jaeger because there is one per SQL statement.
        if span.name == "connect":
            return
        self._inner.on_end(span)

    def shutdown(self) -> None:
        self._inner.shutdown()

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        return self._inner.force_flush(timeout_millis)


def configure_opentelemetry(app: FastAPI) -> None:
    """Initialize OpenTelemetry tracing for the application.

    Must be called at module level in main.py (after all middleware registrations)
    so that the OTEL middleware is included in the middleware stack from the very
    first compile. When OTEL_ENABLED=False this is a no-op — all OTel API calls
    in the codebase automatically fall back to the SDK's built-in no-op implementations.

    Standard OTel SDK env vars are read directly by the SDK (no need to add them to
    the application Config):
      - OTEL_SERVICE_NAME          — service name in traces (default: "codemie")
      - OTEL_EXPORTER_OTLP_ENDPOINT — OTLP collector endpoint; triggers OTLP export when set
      - OTEL_EXPORTER_OTLP_HEADERS  — "key=val,key2=val2" auth headers for the OTLP exporter
      - OTEL_RESOURCE_ATTRIBUTES    — extra resource tags, e.g. "k8s.cluster.name=dev"
    """
    if not config.OTEL_ENABLED:
        return

    # Resource.create() automatically merges OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES
    # from the environment via OTELResourceDetector.  Explicitly passed attributes take
    # precedence, so SERVICE_NAME is only set here as a default when the env var is absent.
    resource = Resource.create(
        {
            **({ResourceAttributes.SERVICE_NAME: "codemie"} if not os.environ.get("OTEL_SERVICE_NAME") else {}),
            ResourceAttributes.SERVICE_VERSION: config.APP_VERSION,
            ResourceAttributes.DEPLOYMENT_ENVIRONMENT: config.ENV,
            "k8s.pod.name": os.environ.get("POD_NAME", ""),
            "k8s.namespace.name": os.environ.get("POD_NAMESPACE", ""),
        }
    )

    _configure_tracing(resource)

    from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
    from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor

    FastAPIInstrumentor().instrument_app(app, excluded_urls=config.OTEL_EXCLUDED_URLS)
    # Instruments all httpx.Client / httpx.AsyncClient instances globally.
    # Covers LiteLLM outbound calls and any other httpx usage in the codebase.
    HTTPXClientInstrumentor().instrument()
    # SQLAlchemy instrumentation is done in main.py lifespan after engines are created,
    # because PostgresClient uses from-imports that bypass module-level monkey-patching.


def _configure_tracing(resource: Resource) -> None:
    # OTLPSpanExporter() reads OTEL_EXPORTER_OTLP_ENDPOINT and OTEL_EXPORTER_OTLP_HEADERS
    # from the environment automatically — no manual parsing needed.
    exporter = OTLPSpanExporter() if os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT") else ConsoleSpanExporter()

    provider = TracerProvider(resource=resource)
    provider.add_span_processor(_DropAsgiSendSpansProcessor(BatchSpanProcessor(exporter)))
    trace.set_tracer_provider(provider)


def enrich_sqlalchemy_spans(engines: list) -> None:
    """Add the primary table name to SQLAlchemy span names for better visibility.

    Without enrichment, auto-instrumented spans are named only by SQL operation
    ("SELECT", "UPDATE", …), making it hard to identify bottlenecks.  This hook
    renames them to e.g. "SELECT conversations" and adds a ``db.sql.table`` attribute.

    Must be called AFTER ``SQLAlchemyInstrumentor().instrument(engines=[...])``.
    SQLAlchemy fires ``before_cursor_execute`` listeners in registration order, so
    OTel's listener runs first (creating and activating the span) and our listener
    runs second (updating the already-active span name).
    """
    import re

    from sqlalchemy import event

    table_re = re.compile(r"\b(?:FROM|INTO|UPDATE|JOIN)\s+\"?(\w+)\"?", re.IGNORECASE)
    ops = frozenset({"SELECT", "INSERT", "UPDATE", "DELETE", "MERGE"})

    def _before_cursor_execute(conn, cursor, statement, parameters, context, executemany):  # noqa: ARG001
        # OTel SQLAlchemy instrumentation uses tracer.start_span() (not start_as_current_span),
        # so the SQL span is never the "current" span — it's stored in context._otel_span.
        span = getattr(context, "_otel_span", None)
        if span is None or not span.is_recording():
            return
        match = table_re.search(statement)
        if not match:
            return
        table = match.group(1)
        # Span name is "{OP} {db_name}" (e.g. "SELECT codemie_db"); take just the first word.
        op = span.name.split()[0]
        if op.upper() in ops:
            span.update_name(f"{op} {table}")
        span.set_attribute("db.sql.table", table)

    for engine in engines:
        if not event.contains(engine, "before_cursor_execute", _before_cursor_execute):
            event.listen(engine, "before_cursor_execute", _before_cursor_execute)


def get_tracer(name: str) -> Tracer:
    """Return a tracer for the given instrumentation scope."""
    return trace.get_tracer(name)
