[pytest]
testpaths = tests
pythonpath = src
addopts = --import-mode=importlib
env =
    ENV=local
    REPOS_LOCAL_DIR=./codemie-repos
    PG_URL=postgresql://pg:pg123@localhost:111/postgres
filterwarnings =
    ignore::DeprecationWarning
    ignore::RuntimeWarning
