sonar.projectKey=codemie
sonar.projectName=codemie
sonar.exclusions=**/deploy-templates/**,**/charts/**,src/codemie/templates/**,src/codemie/clients/provider/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src/codemie
sonar.tests=tests
sonar.python.version=3.12
