# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import asyncio
import os
import time
from datetime import datetime, timedelta, UTC
from typing import List, Optional

from pydantic import BaseModel, Field
from sqlmodel import select, and_, or_

from codemie.clients.postgres import get_session
from codemie.configs import config, logger
from codemie.core.dependecies import get_llm_by_credentials, set_disable_prompt_cache
from codemie.repository.conversation_analysis_queue_repository import ConversationAnalysisQueueRepository
from codemie.repository.conversation_analytics_repository import ConversationAnalyticsRepository
from codemie.rest_api.models.conversation import Conversation
from codemie.service.conversation_analysis.conversation_analytics_elasticsearch_service import (
    ConversationAnalyticsElasticsearchService,
)
from codemie.service.conversation_analysis.leader_lock import LeaderLockContext
from codemie.rest_api.models.conversation_analysis import (
    ConversationAnalytics,
    AssistantUsed,
    TopicAnalysis,
    SatisfactionMetrics,
    MaturityAnalysis,
    AntiPattern,
)
from codemie.templates.conversation_analysis_prompt import CONVERSATION_ANALYSIS_PROMPT


class ConversationAnalysisSchema(BaseModel):
    """Pydantic schema for LLM-generated analysis output only.

    This schema contains ONLY fields that should be generated by the LLM.
    Static fields (user info, assistant details) are populated separately from conversation data.

    Uses explicit Pydantic models instead of generic dicts to satisfy
    Azure's structured output validation (requires additionalProperties: false).
    """

    class Config:
        extra = "forbid"  # Ensures additionalProperties: false in JSON schema

    topics: List[TopicAnalysis] = Field(
        description="Distinct topics/tasks discussed in the conversation, classified by category and intent. REQUIRED."
    )
    satisfaction: SatisfactionMetrics = Field(
        description="User satisfaction metrics including answer quality, iteration efficiency, "
        "conversation focus, and overall score (1-5). REQUIRED."
    )
    maturity: MaturityAnalysis = Field(
        description="AI maturity level analysis (L1-beginner, L2-intermediate, L3-advanced) "
        "with supporting indicators and justification. REQUIRED."
    )
    anti_patterns: List[AntiPattern] = Field(
        description="Identified inefficiencies and suboptimal usage patterns with severity levels, "
        "examples, and improvement recommendations. Can be empty list."
    )


class ConversationAnalysisService:
    """Service for analyzing conversations using LLM with reprocessing support"""

    def __init__(self):
        self.queue_repo = ConversationAnalysisQueueRepository()
        self.analytics_repo = ConversationAnalyticsRepository()

    async def schedule_analysis_job(self, projects: Optional[List[str]] = None) -> dict:
        """
        Main entry point called by APScheduler.
        Handles leader election and queue population.

        Uses PostgreSQL advisory locks for distributed leader election to ensure
        only one pod populates the queue at a time. The lock is automatically
        released when the context exits, even if an exception occurs.

        Args:
            projects: Optional list of project names to filter conversations.
                     If None, analyzes conversations from all projects.

        Returns:
            Dict with job execution summary
        """
        if not config.CONVERSATION_ANALYSIS_ENABLED:
            logger.info("Conversation analysis is disabled via config")
            return {"status": "disabled"}

        # Use context manager for leader lock - ensures proper lock lifecycle
        with LeaderLockContext() as leader_lock:
            if not leader_lock.acquired:
                logger.info("Another pod is already leading conversation analysis, skipping")
                return {"status": "skipped", "reason": "not_leader"}

            # This pod is the leader
            logger.info("This pod is the leader for conversation analysis")

            # Fetch conversations needing analysis (including reprocessing candidates)
            # Use asyncio.to_thread to prevent blocking the event loop
            conversations_to_analyze = await asyncio.to_thread(self._fetch_conversations_for_analysis, projects)

            if not conversations_to_analyze:
                logger.info("No conversations to analyze")
                return {"status": "success", "conversations_queued": 0}

            # Populate queue
            queued_count = await self.queue_repo.add_conversations_to_queue(
                [conv.conversation_id for conv in conversations_to_analyze]
            )

            logger.info(
                f"Queued {queued_count} conversations for distributed analysis "
                f"({len(conversations_to_analyze)} candidates found)"
            )

            return {
                "status": "success",
                "conversations_queued": queued_count,
                "conversations_found": len(conversations_to_analyze),
            }

        # Lock automatically released here by context manager __exit__

    async def process_batch(self, batch_size: int | None = None) -> dict:
        """
        Process a batch of conversations from the queue.
        Called by all pods in a loop.

        Args:
            batch_size: Number of conversations to process (uses config default if None)

        Returns:
            Dict with processing summary
        """
        if not config.CONVERSATION_ANALYSIS_ENABLED:
            return {"status": "disabled"}

        batch_size = batch_size or config.CONVERSATION_ANALYSIS_BATCH_SIZE
        pod_name = os.environ.get("HOSTNAME", "unknown-pod")

        # Claim batch from queue
        claimed_items = await self.queue_repo.claim_batch_for_processing(
            batch_size=batch_size, pod_name=pod_name, max_retries=config.CONVERSATION_ANALYSIS_MAX_RETRIES
        )

        if not claimed_items:
            return {"status": "no_work", "processed": 0}

        success_count = 0
        failure_count = 0
        updated_count = 0
        created_count = 0

        for queue_item in claimed_items:
            try:
                # Analyze conversation
                # Use asyncio.to_thread to prevent blocking the event loop during LLM/DB operations
                analytics = await asyncio.to_thread(self._analyze_conversation, queue_item.conversation_id)

                # Save result to PostgreSQL (UPSERT)
                saved_analytics, is_new = await self.analytics_repo.upsert_analysis(analytics)

                # Index to Elasticsearch for analytics/dashboard queries
                # Use asyncio.to_thread for Elasticsearch I/O (non-critical, errors logged but not raised)
                await asyncio.to_thread(ConversationAnalyticsElasticsearchService.index_analytics, saved_analytics)

                if is_new:
                    created_count += 1
                else:
                    updated_count += 1

                # Mark queue item as completed
                await self.queue_repo.mark_completed(queue_item.id)

                success_count += 1

            except Exception as e:
                logger.error(f"Failed to analyze conversation {queue_item.conversation_id}: {e}", exc_info=True)
                await self.queue_repo.mark_failed(queue_item.id, error_message=str(e))
                failure_count += 1

        logger.info(
            f"Batch processing complete: {success_count} successful "
            f"({created_count} new, {updated_count} updated), {failure_count} failed"
        )

        return {
            "status": "success",
            "processed": success_count + failure_count,
            "successful": success_count,
            "failed": failure_count,
            "new_analyses": created_count,
            "reprocessed": updated_count,
        }

    def _fetch_conversations_for_analysis(self, projects: Optional[List[str]] = None) -> List[Conversation]:
        """
        Fetch conversations that need analysis (including reprocessing).

        Criteria (ALL must be met):
        1. conversation.date >= CONVERSATION_ANALYSIS_START_DATE OR
           conversation.update_date >= CONVERSATION_ANALYSIS_START_DATE
        2. conversation.update_date < (NOW - CONVERSATION_ANALYSIS_LOOKBACK_DAYS)
        3. (Optional) If projects is provided, conversation.project must be in the list
        4. AND one of:
           a) Never analyzed (no record in conversation_analytics), OR
           b) Updated since last analysis (conversation.update_date > analytics.last_analysis_date), OR
           c) Message count increased (len(conversation.history) > analytics.message_count_at_analysis)

        Args:
            projects: Optional list of project names to filter conversations.
                     If None, retrieves conversations from all projects.

        Returns:
            List of Conversation objects needing analysis
        """
        # Parse start date
        start_date = datetime.strptime(config.CONVERSATION_ANALYSIS_START_DATE, "%Y-%m-%d")

        lookback_date = datetime.now(UTC) - timedelta(days=config.CONVERSATION_ANALYSIS_LOOKBACK_DAYS)

        projects_info = f"projects={projects}" if projects else "all projects"
        logger.info(
            f"Fetching conversations for analysis: start_date={start_date}, "
            f"lookback_date={lookback_date}, {projects_info}"
        )

        with get_session() as session:
            # Build WHERE conditions
            where_conditions = [
                # Criterion 1: Within start date range
                or_(Conversation.date >= start_date, Conversation.update_date >= start_date),
                # Criterion 2: Old enough to analyze
                Conversation.update_date < lookback_date,
            ]

            # Criterion 3: Optional project filter
            if projects:
                where_conditions.append(Conversation.project.in_(projects))

            # Query conversations meeting date criteria
            base_stmt = (
                select(Conversation, ConversationAnalytics)
                .outerjoin(ConversationAnalytics, Conversation.conversation_id == ConversationAnalytics.conversation_id)
                .where(and_(*where_conditions))
            )

            results = session.exec(base_stmt).all()

            # Filter for reprocessing criteria (Python-level for complex logic)
            conversations_to_analyze = []

            for conversation, analytics in results:
                needs_analysis = False

                if analytics is None:
                    # Criterion 3a: Never analyzed
                    needs_analysis = True
                    logger.debug(f"Conversation {conversation.conversation_id}: never analyzed")
                else:
                    # Criterion 3b: Updated since last analysis
                    if conversation.update_date > analytics.last_analysis_date:
                        needs_analysis = True
                        logger.debug(
                            f"Conversation {conversation.conversation_id}: "
                            f"updated since last analysis "
                            f"(conv_update={conversation.update_date}, "
                            f"last_analysis={analytics.last_analysis_date})"
                        )

                    # Criterion 3c: Message count increased
                    current_message_count = len(conversation.history or [])
                    if current_message_count > analytics.message_count_at_analysis:
                        needs_analysis = True
                        logger.debug(
                            f"Conversation {conversation.conversation_id}: "
                            f"message count increased "
                            f"(current={current_message_count}, "
                            f"at_analysis={analytics.message_count_at_analysis})"
                        )

                if needs_analysis:
                    conversations_to_analyze.append(conversation)

            logger.info(
                f"Found {len(conversations_to_analyze)} conversations needing analysis "
                f"(out of {len(results)} conversations checked)"
            )

            return conversations_to_analyze

    def _create_empty_conversation_template(self, conversation: Conversation) -> ConversationAnalytics:
        """
        Create a predefined template for empty conversations (0 messages).

        This avoids unnecessary LLM calls for conversations that were just created
        and have no actual content to analyze.

        Args:
            conversation: Conversation instance with 0 messages

        Returns:
            ConversationAnalytics instance with template data
        """
        return ConversationAnalytics(
            conversation_id=conversation.conversation_id,
            user_id=conversation.user_id,
            user_name=conversation.user_name,
            user_email=None,
            project=conversation.project,
            # Empty lists for conversations with no content
            assistants_used=[],
            topics=[],
            anti_patterns=[],
            # Minimal satisfaction metrics - no exchanges occurred
            satisfaction=None,
            # Maturity level cannot be determined from empty conversation
            maturity=None,
            # Tracking metadata
            last_analysis_date=datetime.now(UTC),
            message_count_at_analysis=0,
            analyzed_at=datetime.now(UTC),
            llm_model_used="template",  # Indicate this was generated from template, not LLM
            analysis_duration_seconds=0.0,  # No LLM call, instant
        )

    def _analyze_conversation(self, conversation_id: str) -> ConversationAnalytics:
        """
        Analyze a single conversation using LLM with structured output.
        For empty conversations (0 messages), returns a predefined template.

        Static fields (user info, assistant details) are populated directly from conversation data.
        Only dynamic analysis fields (topics, satisfaction, maturity, anti-patterns) are generated by LLM.

        Args:
            conversation_id: ID of conversation to analyze

        Returns:
            ConversationAnalytics instance with analysis results
        """
        start_time = time.time()
        llm_model = config.CONVERSATION_ANALYSIS_LLM_MODEL
        # Fetch conversation
        conversation = Conversation.get_by_id(conversation_id)

        # Check message count - skip LLM analysis for empty conversations
        current_message_count = len(conversation.history or [])
        if current_message_count == 0:
            logger.info(f"Conversation {conversation_id} has 0 messages, using template instead of LLM")
            return self._create_empty_conversation_template(conversation)

        # Fetch static data from conversation (not from LLM)
        assistants_used = self._fetch_assistant_details(conversation.assistant_ids or [])

        # Convert conversation history to text format
        conversation_text = self._format_conversation_for_llm(conversation)
        # Get LLM with structured output
        set_disable_prompt_cache(disable=True)
        llm = get_llm_by_credentials(llm_model=llm_model, streaming=False, request_id=conversation_id)

        # Apply structured output schema
        llm_with_structured_output = llm.with_structured_output(ConversationAnalysisSchema)

        # Build prompt directly to avoid format string issues with conversation text
        # (conversation may contain curly braces from JSON, code snippets, etc.)
        prompt_text = CONVERSATION_ANALYSIS_PROMPT.template.replace("{conversation}", conversation_text)

        logger.debug(f"Analyzing conversation {conversation_id} with LLM")
        structured_output = llm_with_structured_output.invoke(prompt_text)

        # Combine static fields (from conversation data) with LLM-generated analysis
        analytics = ConversationAnalytics(
            conversation_id=conversation_id,
            # Static fields from conversation data
            user_id=conversation.user_id,
            user_name=conversation.user_name,
            project=conversation.project,
            assistants_used=assistants_used,
            # LLM-generated analysis fields
            topics=structured_output.topics,
            satisfaction=structured_output.satisfaction,
            maturity=structured_output.maturity,
            anti_patterns=structured_output.anti_patterns,
            # Reprocessing tracking
            last_analysis_date=datetime.now(UTC),
            message_count_at_analysis=current_message_count,
            # Metadata
            analyzed_at=datetime.now(UTC),
            llm_model_used=llm_model,
            analysis_duration_seconds=time.time() - start_time,
        )

        logger.info(
            f"Completed analysis of conversation {conversation_id} "
            f"({current_message_count} messages) "
            f"in {analytics.analysis_duration_seconds:.2f}s"
        )

        return analytics

    def _extract_toolkit_tool_names(self, assistant) -> List[str]:
        """
        Extract tool names from assistant toolkits.

        Args:
            assistant: Assistant instance

        Returns:
            List of tool names from toolkits
        """
        tool_names = []
        for toolkit in assistant.toolkits or []:
            for tool in toolkit.tools or []:
                if tool.name:
                    tool_names.append(tool.name)
        return tool_names

    def _extract_mcp_tool_names(self, assistant) -> List[str]:
        """
        Extract tool names from MCP servers.

        Args:
            assistant: Assistant instance

        Returns:
            List of MCP tool names
        """
        mcp_tool_names = []
        for mcp_server in assistant.mcp_servers or []:
            if mcp_server.enabled and mcp_server.name:
                # Add MCP server name as tool identifier
                mcp_tool_names.append(f"MCP:{mcp_server.name}")
                # Add specific tool names if available
                if mcp_server.tools:
                    mcp_tool_names.extend([f"MCP:{mcp_server.name}:{tool}" for tool in mcp_server.tools])
        return mcp_tool_names

    def _build_assistant_used(self, assistant) -> AssistantUsed:
        """
        Build AssistantUsed object from assistant instance.

        Args:
            assistant: Assistant instance

        Returns:
            AssistantUsed object with full details
        """
        # Extract tool names
        tool_names = self._extract_toolkit_tool_names(assistant)
        tool_names.extend(self._extract_mcp_tool_names(assistant))

        # Extract datasource names
        datasource_names = [ctx.name for ctx in assistant.context or []]

        # Get author name
        author_name = assistant.created_by.name if assistant.created_by else None

        return AssistantUsed(
            id=assistant.id,
            name=assistant.name,
            description=assistant.description,
            categories=assistant.categories or [],
            author=author_name,
            tool_names=tool_names,
            datasource_names=datasource_names,
        )

    def _fetch_assistant_details(self, assistant_ids: List[str]) -> List[AssistantUsed]:
        """
        Fetch full assistant details for given assistant IDs.

        Args:
            assistant_ids: List of assistant IDs

        Returns:
            List of AssistantUsed objects with full details
        """
        if not assistant_ids:
            return []

        from codemie.rest_api.models.assistant import Assistant

        try:
            # Fetch assistants from database
            assistants = Assistant.get_by_ids_no_permission_check(assistant_ids)

            # Build assistant details using helper method
            return [self._build_assistant_used(assistant) for assistant in assistants]

        except Exception as e:
            logger.error(f"Failed to fetch assistant details: {e}", exc_info=True)
            # Return minimal info on error
            return [AssistantUsed(id=aid, name=f"Unknown ({aid})") for aid in assistant_ids]

    def _format_conversation_metadata(self, conversation: Conversation) -> List[str]:
        """
        Format conversation metadata (header info).

        Args:
            conversation: Conversation instance

        Returns:
            List of formatted metadata lines
        """
        return [
            f"Conversation ID: {conversation.conversation_id}",
            f"User: {conversation.user_name} ({conversation.user_id})",
            f"Created: {conversation.date}",
            f"Last Updated: {conversation.update_date}",
            f"Message Count: {len(conversation.history or [])}",
        ]

    def _format_assistant_section(self, assistant: AssistantUsed) -> List[str]:
        """
        Format a single assistant's details for LLM prompt.

        Args:
            assistant: AssistantUsed instance

        Returns:
            List of formatted lines for the assistant
        """
        tools_str = ", ".join(assistant.tool_names) if assistant.tool_names else "None"
        datasources_str = ", ".join(assistant.datasource_names) if assistant.datasource_names else "None"
        categories_str = ", ".join(assistant.categories) if assistant.categories else "None"

        return [
            f"Assistant ID: {assistant.id}",
            f"  Name: {assistant.name}",
            f"  Description: {assistant.description or 'N/A'}",
            f"  Categories: {categories_str}",
            f"  Author: {assistant.author or 'N/A'}",
            f"  Selected Tools: {tools_str}",
            f"  Datasources: {datasources_str}",
            "",
        ]

    def _format_assistants_section(self, assistant_ids: List[str]) -> List[str]:
        """
        Format all assistants section for LLM prompt.

        Args:
            assistant_ids: List of assistant IDs

        Returns:
            List of formatted lines for all assistants
        """
        assistant_details = self._fetch_assistant_details(assistant_ids)
        if not assistant_details:
            return []

        lines = ["\n--- Assistants Used ---\n"]
        for assistant in assistant_details:
            lines.extend(self._format_assistant_section(assistant))

        return lines

    def _format_tool_invocation(self, thought, timestamp: str) -> List[str]:
        """
        Format a single tool invocation for LLM prompt.

        Args:
            thought: Thought instance containing tool invocation
            timestamp: Formatted timestamp string

        Returns:
            List of formatted lines for the tool invocation
        """
        tool_name = thought.author_name
        tool_input = thought.input_text or "N/A"
        tool_status = "FAILED" if thought.error else "SUCCESS"

        # Truncate long inputs for readability (keep first 500 chars)
        if len(tool_input) > 500:
            tool_input = tool_input[:500] + "... (truncated)"

        return [
            f"[{timestamp}] [TOOL INVOCATION] Tool: {tool_name}",
            f"  Input: {tool_input}",
            f"  Status: {tool_status}\n",
        ]

    def _format_message_with_tools(self, msg, role: str, timestamp: str) -> List[str]:
        """
        Format a message with its tool invocations.

        Args:
            msg: Message instance
            role: Formatted role string (e.g., "USER", "ASSISTANT")
            timestamp: Formatted timestamp string

        Returns:
            List of formatted lines for the message and its tools
        """
        lines = []

        # For assistant messages, show tool invocations FIRST (before the response)
        if role == "ASSISTANT" and msg.thoughts:
            for thought in msg.thoughts:
                if thought.author_type == "Tool" and thought.author_name:
                    lines.extend(self._format_tool_invocation(thought, timestamp))

        # Then show the message content
        content = msg.message or ""
        lines.append(f"[{timestamp}] {role}: {content}\n")

        return lines

    def _format_conversation_history(self, conversation: Conversation) -> List[str]:
        """
        Format conversation history for LLM prompt.

        Args:
            conversation: Conversation instance

        Returns:
            List of formatted lines for conversation history
        """
        lines = ["\n--- Conversation History ---\n"]

        for msg in conversation.history or []:
            # Extract essential message data (role, content, timestamp)
            role = msg.role.upper() if hasattr(msg.role, "upper") else str(msg.role).upper()
            timestamp = msg.date.strftime("%Y-%m-%d %H:%M:%S") if msg.date else "N/A"

            lines.extend(self._format_message_with_tools(msg, role, timestamp))

        return lines

    def _format_conversation_for_llm(self, conversation: Conversation) -> str:
        """
        Format conversation history into text for LLM prompt.

        Includes assistant details as context for LLM analysis (especially for anti-pattern detection).
        Note: Assistant details are provided as INPUT for analysis, not for extraction into output schema.
        The LLM uses this context to identify issues like wrong assistant selection or missing tools.

        Excludes tool invocation details from message thoughts to keep prompt size manageable.
        Similar to GetRawConversationsTool with full_mode=False.

        Args:
            conversation: Conversation instance

        Returns:
            Formatted text string with assistant context and conversation history
        """
        lines = []

        # Add metadata
        lines.extend(self._format_conversation_metadata(conversation))

        # Add assistants section
        lines.extend(self._format_assistants_section(conversation.assistant_ids or []))

        # Add conversation history
        lines.extend(self._format_conversation_history(conversation))

        return "\n".join(lines)
