# Copyright 2026 EPAM Systems, Inc. (“EPAM”)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pytest
from unittest.mock import patch

from codemie.service.settings.settings import SettingsService
from codemie.rest_api.models.settings import Settings, SettingType, CredentialValues
from codemie_tools.base.models import CredentialTypes


@pytest.fixture
def regular_user_setting():
    """Regular user setting without internal IDE prefix."""
    return Settings(
        id="regular-setting-id",
        user_id="user123",
        project_name="test_project",
        alias="my-jira-integration",
        credential_type=CredentialTypes.JIRA,
        credential_values=[
            CredentialValues(key="url", value="https://test-jira.example.com"),
            CredentialValues(key="token", value="test-fake-token-12345"),
        ],
        setting_type=SettingType.USER,
    )


@pytest.fixture
def ide_internal_setting():
    """Internal IDE setting with __internal__IDE_ prefix."""
    return Settings(
        id="ide-setting-id",
        user_id="user123",
        project_name=SettingsService.IDE_PROJECT_NAME,
        alias="__internal__IDE_a70f1383-12ab-45cd-89ef-1234567890ab",
        credential_type=CredentialTypes.PLUGIN,
        credential_values=[
            CredentialValues(key="plugin_key", value="test-fake-ide-plugin-key-00000"),
            CredentialValues(key="url", value="AutoGenerated"),
        ],
        setting_type=SettingType.USER,
    )


@pytest.fixture
def another_ide_internal_setting():
    """Another internal IDE setting with __internal__IDE_ prefix."""
    return Settings(
        id="ide-setting-id-2",
        user_id="user123",
        project_name=SettingsService.IDE_PROJECT_NAME,
        alias="__internal__IDE_9579e6f0f-56gh-78ij-90kl-9876543210mn",
        credential_type=CredentialTypes.PLUGIN,
        credential_values=[
            CredentialValues(key="plugin_key", value="test-fake-ide-plugin-key-99999"),
            CredentialValues(key="url", value="AutoGenerated"),
        ],
        setting_type=SettingType.USER,
    )


@pytest.fixture
def project_setting():
    """Project-level setting."""
    return Settings(
        id="project-setting-id",
        user_id=None,
        project_name="test_project",
        alias="project-aws-integration",
        credential_type=CredentialTypes.AWS,
        credential_values=[
            CredentialValues(key="aws_access_key_id", value="TEST_FAKE_AWS_KEY_ID_00000"),
            CredentialValues(key="aws_secret_access_key", value="TEST_FAKE_AWS_SECRET_KEY_00000_NOT_REAL"),
        ],
        setting_type=SettingType.PROJECT,
    )


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_filters_out_ide_internal_settings(
    mock_get_by_user_id, regular_user_setting, ide_internal_setting
):
    """Test that internal IDE settings are filtered out from user settings."""
    # Given: Database returns both regular and internal IDE settings
    mock_get_by_user_id.return_value = [regular_user_setting, ide_internal_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(
        user_id="user123", project_names=None, settings_type=None, credential_type=None
    )

    # Then: Only regular setting is returned, IDE setting is filtered out
    assert len(result) == 1
    assert result[0].alias == "my-jira-integration"
    assert not result[0].alias.startswith(SettingsService.INTERNAL_PREFIX)
    mock_get_by_user_id.assert_called_once_with("user123", credential_type=None)


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_filters_multiple_ide_internal_settings(
    mock_get_by_user_id, regular_user_setting, ide_internal_setting, another_ide_internal_setting
):
    """Test that multiple internal IDE settings are all filtered out."""
    # Given: Database returns one regular and two internal IDE settings
    mock_get_by_user_id.return_value = [regular_user_setting, ide_internal_setting, another_ide_internal_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Only regular setting is returned, both IDE settings are filtered out
    assert len(result) == 1
    assert result[0].alias == "my-jira-integration"
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_returns_empty_when_only_ide_settings(mock_get_by_user_id, ide_internal_setting):
    """Test that empty list is returned when only internal IDE settings exist."""
    # Given: Database returns only internal IDE settings
    mock_get_by_user_id.return_value = [ide_internal_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Empty list is returned
    assert len(result) == 0
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_returns_all_when_no_ide_settings(mock_get_by_user_id, regular_user_setting, project_setting):
    """Test that all settings are returned when none are internal IDE settings."""
    # Given: Database returns only regular settings (no IDE settings)
    mock_get_by_user_id.return_value = [regular_user_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: All settings are returned
    assert len(result) == 1
    assert result[0].alias == "my-jira-integration"
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_handles_none_alias(mock_get_by_user_id):
    """Test that settings with None alias are not filtered out."""
    # Given: Database returns setting with None alias
    setting_with_none_alias = Settings(
        id="none-alias-id",
        user_id="user123",
        project_name="test_project",
        alias=None,
        credential_type=CredentialTypes.AWS,
        credential_values=[CredentialValues(key="url", value="https://test-aws.example.com")],
        setting_type=SettingType.USER,
    )
    mock_get_by_user_id.return_value = [setting_with_none_alias]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Setting with None alias is returned
    assert len(result) == 1
    assert result[0].alias is None
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_project_names')
def test_get_settings_filters_internal_project_settings(mock_get_by_project_names, project_setting):
    """Test that internal settings filtering IS applied to project-level settings."""
    # Given: Getting project settings including an internal one
    internal_project_setting = Settings(
        id="internal-project-setting-id",
        user_id=None,
        project_name="test_project",
        alias="__internal__PROJECT_test_setting",
        credential_type=CredentialTypes.AWS,
        credential_values=[
            CredentialValues(key="aws_access_key_id", value="TEST_INTERNAL_KEY"),
        ],
        setting_type=SettingType.PROJECT,
    )
    mock_get_by_project_names.return_value = [project_setting, internal_project_setting]

    # When: Getting project settings
    result = SettingsService.get_settings(
        user_id=None, project_names=["test_project"], settings_type=SettingType.PROJECT, credential_type=None
    )

    # Then: Only regular project setting is returned, internal setting is filtered out
    assert len(result) == 1
    assert result[0].alias == "project-aws-integration"
    mock_get_by_project_names.assert_called_once_with(["test_project"], credential_type=None)


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_with_credential_type_filter(mock_get_by_user_id, regular_user_setting):
    """Test that credential_type filtering works along with IDE filtering."""
    # Given: Database returns settings filtered by credential type
    mock_get_by_user_id.return_value = [regular_user_setting]

    # When: Getting user settings with credential type filter
    result = SettingsService.get_settings(user_id="user123", credential_type=CredentialTypes.JIRA)

    # Then: Settings are returned with credential type filter applied
    assert len(result) == 1
    assert result[0].credential_type == CredentialTypes.JIRA
    mock_get_by_user_id.assert_called_once_with("user123", credential_type=CredentialTypes.JIRA)


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_masks_sensitive_fields(mock_get_by_user_id, regular_user_setting):
    """Test that sensitive fields are masked in returned settings."""
    # Given: Database returns settings with sensitive data
    mock_get_by_user_id.return_value = [regular_user_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Sensitive fields should be masked
    assert len(result) == 1
    # Check that token value is masked (hide_sensitive_fields should mask it)
    token_value = next((cv.value for cv in result[0].credential_values if cv.key == "token"), None)
    assert token_value == "**********"  # Masked value
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_with_empty_result(mock_get_by_user_id):
    """Test that empty list is handled correctly."""
    # Given: Database returns empty list
    mock_get_by_user_id.return_value = []

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Empty list is returned
    assert len(result) == 0
    assert result == []
    mock_get_by_user_id.assert_called_once()


@patch.object(Settings, 'get_by_user_id')
def test_get_settings_preserves_order(
    mock_get_by_user_id, regular_user_setting, ide_internal_setting, another_ide_internal_setting
):
    """Test that order of non-IDE settings is preserved after filtering."""
    # Given: Create multiple regular settings to test ordering
    setting1 = Settings(
        id="setting-1",
        user_id="user123",
        project_name="test_project",
        alias="first-integration",
        credential_type=CredentialTypes.JIRA,
        credential_values=[CredentialValues(key="url", value="https://test-first.example.com")],
        setting_type=SettingType.USER,
    )
    setting2 = Settings(
        id="setting-2",
        user_id="user123",
        project_name="test_project",
        alias="second-integration",
        credential_type=CredentialTypes.GIT,
        credential_values=[CredentialValues(key="url", value="https://test-second.example.com")],
        setting_type=SettingType.USER,
    )

    # Mix IDE and regular settings
    mock_get_by_user_id.return_value = [setting1, ide_internal_setting, setting2, another_ide_internal_setting]

    # When: Getting user settings
    result = SettingsService.get_settings(user_id="user123")

    # Then: Order of regular settings is preserved
    assert len(result) == 2
    assert result[0].alias == "first-integration"
    assert result[1].alias == "second-integration"


@patch.object(Settings, 'get_by_user_id')
@patch.object(Settings, 'get_by_project_names')
def test_get_user_litellm_api_keys_returns_grouped_keys(mock_get_by_project_names, mock_get_by_user_id):
    """Test get_user_litellm_api_keys returns API keys grouped by USER and PROJECT."""
    # Given: USER-scoped LiteLLM settings
    user_setting1 = Settings(
        id="user-setting-1",
        user_id="user123",
        project_name="user-project",
        alias="user-litellm-1",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="user-api-key-1"),
            CredentialValues(key="url", value="https://litellm.example.com"),
        ],
        setting_type=SettingType.USER,
    )
    user_setting2 = Settings(
        id="user-setting-2",
        user_id="user123",
        project_name="user-project",
        alias="user-litellm-2",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="user-api-key-2"),
        ],
        setting_type=SettingType.USER,
    )

    # Given: PROJECT-scoped LiteLLM settings
    project_setting1 = Settings(
        id="project-setting-1",
        user_id=None,
        project_name="project-1",
        alias="project-litellm-1",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="project-api-key-1"),
        ],
        setting_type=SettingType.PROJECT,
    )

    mock_get_by_user_id.return_value = [user_setting1, user_setting2]
    mock_get_by_project_names.return_value = [project_setting1]

    # When: Getting user's LiteLLM API keys
    result = SettingsService.get_user_litellm_api_keys("user123", ["project-1", "project-2"])

    # Then: Keys are grouped by type
    assert "user_keys" in result
    assert "project_keys" in result
    assert len(result["user_keys"]) == 2
    assert "user-api-key-1" in result["user_keys"]
    assert "user-api-key-2" in result["user_keys"]
    assert len(result["project_keys"]) == 1
    assert "project-api-key-1" in result["project_keys"]

    # Verify correct queries were made
    mock_get_by_user_id.assert_called_once_with("user123", CredentialTypes.LITE_LLM)
    mock_get_by_project_names.assert_called_once_with(["project-1", "project-2"], CredentialTypes.LITE_LLM)


@patch.object(Settings, 'get_by_user_id')
@patch.object(Settings, 'get_by_project_names')
def test_get_user_litellm_api_keys_deduplicates_by_setting_id(mock_get_by_project_names, mock_get_by_user_id):
    """Test that settings with same ID are deduplicated."""
    # Given: Settings with duplicate IDs
    user_setting = Settings(
        id="same-setting-id",
        user_id="user123",
        project_name="user-project",
        alias="litellm-setting",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="api-key-1"),
        ],
        setting_type=SettingType.USER,
    )

    project_setting = Settings(
        id="same-setting-id",  # Same ID - should be deduplicated
        user_id=None,
        project_name="project-1",
        alias="litellm-setting",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="api-key-1"),
        ],
        setting_type=SettingType.PROJECT,
    )

    mock_get_by_user_id.return_value = [user_setting]
    mock_get_by_project_names.return_value = [project_setting]

    # When: Getting user's LiteLLM API keys
    result = SettingsService.get_user_litellm_api_keys("user123", ["project-1"])

    # Then: Only one key is included (deduplicated)
    total_keys = len(result["user_keys"]) + len(result["project_keys"])
    assert total_keys == 1


@patch.object(Settings, 'get_by_user_id')
@patch.object(Settings, 'get_by_project_names')
def test_get_user_litellm_api_keys_skips_settings_without_api_key(mock_get_by_project_names, mock_get_by_user_id):
    """Test that settings without api_key field are skipped."""
    # Given: Setting without api_key field
    setting_no_key = Settings(
        id="setting-no-key",
        user_id="user123",
        project_name="user-project",
        alias="litellm-no-key",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="url", value="https://litellm.example.com"),
            CredentialValues(key="other", value="value"),
        ],
        setting_type=SettingType.USER,
    )

    # Given: Valid setting with api_key
    setting_with_key = Settings(
        id="setting-with-key",
        user_id="user123",
        project_name="user-project",
        alias="litellm-with-key",
        credential_type=CredentialTypes.LITE_LLM,
        credential_values=[
            CredentialValues(key="api_key", value="valid-api-key"),
        ],
        setting_type=SettingType.USER,
    )

    mock_get_by_user_id.return_value = [setting_no_key, setting_with_key]
    mock_get_by_project_names.return_value = []

    # When: Getting user's LiteLLM API keys
    result = SettingsService.get_user_litellm_api_keys("user123", [])

    # Then: Only the setting with api_key is included
    assert len(result["user_keys"]) == 1
    assert "valid-api-key" in result["user_keys"]
    assert len(result["project_keys"]) == 0


@patch.object(Settings, 'get_by_user_id')
@patch.object(Settings, 'get_by_project_names')
def test_get_user_litellm_api_keys_handles_empty_settings(mock_get_by_project_names, mock_get_by_user_id):
    """Test that empty settings lists are handled correctly."""
    # Given: No settings found
    mock_get_by_user_id.return_value = []
    mock_get_by_project_names.return_value = []

    # When: Getting user's LiteLLM API keys
    result = SettingsService.get_user_litellm_api_keys("user123", ["project-1"])

    # Then: Empty lists are returned
    assert result["user_keys"] == []
    assert result["project_keys"] == []
