# An example config with authorized applications to create permissions for
authorized_applications: []
  # - name: test_app 
  #   public_key_url: <some_url>
  #   # public_key_path: ./key.pem
  #   allowed_resources: 
  #     - datasource