apiVersion: v2
name: codemie
description: A Helm chart for AI/Run API
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://codemie.lab.epam.com
sources:
  - https://gitbud.epam.com/epm-cdme/codemie.git
maintainers:
  - name: AI/Run
    email: SpecialEPM-CDMEDevelopmentTeam@epam.com
