# coding: utf-8

# flake8: noqa
"""
Service Provider Interface (SPI) OpenAPI

OpenAPI 3.1 specification defining the endpoints and data models for any external service provider (e.g., AICE) integrating with the AI/Run Platform.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from codemie.clients.provider.client.models.error_response import ErrorResponse
from codemie.clients.provider.client.models.health_response import HealthResponse
from codemie.clients.provider.client.models.tool_invocation_request import ToolInvocationRequest
from codemie.clients.provider.client.models.tool_invocation_response import ToolInvocationResponse
from codemie.clients.provider.client.models.toolkit_configuration import ToolkitConfiguration
