# coding: utf-8

"""
Service Provider Interface (SPI) OpenAPI

OpenAPI 3.1 specification defining the endpoints and data models for any external service provider (e.g., AICE) integrating with the AI/Run Platform.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class HealthResponse(BaseModel):
    """
    HealthResponse
    """  # noqa: E501

    status: Optional[StrictStr] = None
    provider_version: Optional[StrictStr] = Field(default=None, alias="providerVersion")
    uptime: Optional[StrictInt] = Field(default=None, description="Service uptime in seconds.")
    timestamp: Optional[datetime] = Field(default=None, description="Timestamp of the health check.")
    extra_info: Optional[Dict[str, Any]] = Field(
        default=None, description="Additional information about a provider state."
    )
    __properties: ClassVar[List[str]] = ["status", "providerVersion", "uptime", "timestamp", "extra_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HealthResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HealthResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "providerVersion": obj.get("providerVersion"),
                "uptime": obj.get("uptime"),
                "timestamp": obj.get("timestamp"),
                "extra_info": obj.get("extra_info"),
            }
        )
        return _obj
