# coding: utf-8

"""
Service Provider Interface (SPI) OpenAPI

OpenAPI 3.1 specification defining the endpoints and data models for any external service provider (e.g., AICE) integrating with the AI/Run Platform.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from codemie.clients.provider.client.models.toolkit_configuration import ToolkitConfiguration
from typing import Optional, Set
from typing_extensions import Self


class ToolInvocationRequest(BaseModel):
    """
    ToolInvocationRequest
    """  # noqa: E501

    user_id: Optional[StrictStr] = Field(default=None, description="User ID of the data source owner.")
    project_id: Optional[StrictStr] = Field(default=None, description="Project ID of the data source.")
    configuration: Optional[ToolkitConfiguration] = None
    parameters: Dict[str, Any] = Field(description="Tool-specific configuration or input")
    var_async: Optional[StrictBool] = Field(
        default=False,
        description="If true, the tool invocation is asynchronous. The response will contain the invocation_id.",
        alias="async",
    )
    callback_url: Optional[StrictStr] = Field(
        default=None, description="URL to which the tool invocation response will be sent. Required if async is true."
    )
    __properties: ClassVar[List[str]] = [
        "user_id",
        "project_id",
        "configuration",
        "parameters",
        "async",
        "callback_url",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolInvocationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of configuration
        if self.configuration:
            _dict['configuration'] = self.configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolInvocationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "user_id": obj.get("user_id"),
                "project_id": obj.get("project_id"),
                "configuration": ToolkitConfiguration.from_dict(obj["configuration"])
                if obj.get("configuration") is not None
                else None,
                "parameters": obj.get("parameters"),
                "async": obj.get("async") if obj.get("async") is not None else False,
                "callback_url": obj.get("callback_url"),
            }
        )
        return _obj
