# coding: utf-8

"""
Service Provider Interface (SPI) OpenAPI

OpenAPI 3.1 specification defining the endpoints and data models for any external service provider (e.g., AICE) integrating with the AI/Run Platform.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class ToolInvocationResponse(BaseModel):
    """
    ToolInvocationResponse
    """  # noqa: E501

    invocation_id: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    result: Optional[Any] = Field(default=None, description="Immediate result if the operation is synchronous")
    result_type: Optional[StrictStr] = Field(default=None, description="Type of the result returned by the tool.")
    warnings: Optional[StrictStr] = Field(default=None, description="Warnings if any")
    errors: Optional[StrictStr] = Field(default=None, description="Errors if any")
    __properties: ClassVar[List[str]] = ["invocation_id", "status", "result", "result_type", "warnings", "errors"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Started', 'InProgress', 'Completed', 'Error']):
            raise ValueError("must be one of enum values ('Started', 'InProgress', 'Completed', 'Error')")
        return value

    @field_validator('result_type')
    def result_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Integer', 'Float', 'String', 'Bytes', 'Bool', 'Json', 'Yaml']):
            raise ValueError(
                "must be one of enum values ('Integer', 'Float', 'String', 'Bytes', 'Bool', 'Json', 'Yaml')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolInvocationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolInvocationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "invocation_id": obj.get("invocation_id"),
                "status": obj.get("status"),
                "result": obj.get("result"),
                "result_type": obj.get("result_type"),
                "warnings": obj.get("warnings"),
                "errors": obj.get("errors"),
            }
        )
        return _obj
