{{- if not .Values.argoRollout.enabled }}
{{- if .Values.security.processAuthSecret.create }}
{{- $secretName := (include "codemie.processAuthSecretName" .) }}
{{- $secretFieldName := (include "codemie.processAuthSecretField" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $secretKeyValue := "" }}
{{- if $existingSecret }}
  {{- $secretKeyValue = index $existingSecret.data $secretFieldName }}
{{- else }}
  {{- $secretKeyValue = printf "%x" (randAscii 32) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "codemie.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $secretFieldName }}: {{ $secretKeyValue | b64enc }}
{{- end }}
{{- end }}
