# coding: utf-8

"""
Service Provider Interface (SPI) OpenAPI

OpenAPI 3.1 specification defining the endpoints and data models for any external service provider (e.g., AICE) integrating with the AI/Run Platform.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from codemie.clients.provider.client.models.tool_invocation_request import ToolInvocationRequest
from codemie.clients.provider.client.models.tool_invocation_response import ToolInvocationResponse

from codemie.clients.provider.client.api_client import ApiClient, RequestSerialized
from codemie.clients.provider.client.api_response import ApiResponse
from codemie.clients.provider.client.rest import RESTResponseType


class ToolInvocationManagementApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def cancel_tool_invocation(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Cancel Tool Invocation

        Attempts to stop a long-running or unwanted tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._cancel_tool_invocation_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '409': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def cancel_tool_invocation_with_http_info(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Cancel Tool Invocation

        Attempts to stop a long-running or unwanted tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._cancel_tool_invocation_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '409': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def cancel_tool_invocation_without_preload_content(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cancel Tool Invocation

        Attempts to stop a long-running or unwanted tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._cancel_tool_invocation_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '409': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _cancel_tool_invocation_serialize(
        self,
        toolkit_name,
        tool_name,
        invocation_id,
        x_correlation_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if toolkit_name is not None:
            _path_params['toolkit_name'] = toolkit_name
        if tool_name is not None:
            _path_params['tool_name'] = tool_name
        if invocation_id is not None:
            _path_params['invocation_id'] = invocation_id
        # process the query parameters
        # process the header parameters
        if x_correlation_id is not None:
            _header_params['X-Correlation-Id'] = x_correlation_id
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['bearerAuth']

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/tools/{toolkit_name}/{tool_name}/invocations/{invocation_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def get_tool_invocation_status(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ToolInvocationResponse:
        """Get Tool Invocation Status

        Retrieves the status or result of a previously invoked tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_tool_invocation_status_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_tool_invocation_status_with_http_info(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ToolInvocationResponse]:
        """Get Tool Invocation Status

        Retrieves the status or result of a previously invoked tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_tool_invocation_status_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_tool_invocation_status_without_preload_content(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        invocation_id: Annotated[StrictStr, Field(description="Identifier of the tool invocation")],
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Tool Invocation Status

        Retrieves the status or result of a previously invoked tool operation.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param invocation_id: Identifier of the tool invocation (required)
        :type invocation_id: str
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_tool_invocation_status_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            invocation_id=invocation_id,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_tool_invocation_status_serialize(
        self,
        toolkit_name,
        tool_name,
        invocation_id,
        x_correlation_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if toolkit_name is not None:
            _path_params['toolkit_name'] = toolkit_name
        if tool_name is not None:
            _path_params['tool_name'] = tool_name
        if invocation_id is not None:
            _path_params['invocation_id'] = invocation_id
        # process the query parameters
        # process the header parameters
        if x_correlation_id is not None:
            _header_params['X-Correlation-Id'] = x_correlation_id
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['bearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/tools/{toolkit_name}/{tool_name}/invocations/{invocation_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def invoke_tool(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        tool_invocation_request: ToolInvocationRequest,
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        x_callback_otp: Annotated[
            Optional[StrictStr], Field(description="One-time password for callback authentication")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ToolInvocationResponse:
        """Invoke Tool

        Executes a specific tool.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param tool_invocation_request: (required)
        :type tool_invocation_request: ToolInvocationRequest
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._invoke_tool_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            tool_invocation_request=tool_invocation_request,
            x_correlation_id=x_correlation_id,
            x_callback_otp=x_callback_otp,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '400': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def invoke_tool_with_http_info(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        tool_invocation_request: ToolInvocationRequest,
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ToolInvocationResponse]:
        """Invoke Tool

        Executes a specific tool.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param tool_invocation_request: (required)
        :type tool_invocation_request: ToolInvocationRequest
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._invoke_tool_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            tool_invocation_request=tool_invocation_request,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '400': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def invoke_tool_without_preload_content(
        self,
        toolkit_name: Annotated[StrictStr, Field(description="Identifier of the toolkit.")],
        tool_name: Annotated[StrictStr, Field(description="Identifier of the tool.")],
        tool_invocation_request: ToolInvocationRequest,
        x_correlation_id: Annotated[
            Optional[StrictStr], Field(description="Unique correlation ID for distributed tracing and audit logs")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Invoke Tool

        Executes a specific tool.

        :param toolkit_name: Identifier of the toolkit. (required)
        :type toolkit_name: str
        :param tool_name: Identifier of the tool. (required)
        :type tool_name: str
        :param tool_invocation_request: (required)
        :type tool_invocation_request: ToolInvocationRequest
        :param x_correlation_id: Unique correlation ID for distributed tracing and audit logs
        :type x_correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._invoke_tool_serialize(
            toolkit_name=toolkit_name,
            tool_name=tool_name,
            tool_invocation_request=tool_invocation_request,
            x_correlation_id=x_correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ToolInvocationResponse",
            '400': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _invoke_tool_serialize(
        self,
        toolkit_name,
        tool_name,
        tool_invocation_request,
        x_correlation_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
        x_callback_otp=None,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if toolkit_name is not None:
            _path_params['toolkit_name'] = toolkit_name
        if tool_name is not None:
            _path_params['tool_name'] = tool_name
        # process the query parameters
        # process the header parameters
        if x_correlation_id is not None:
            _header_params['X-Correlation-Id'] = x_correlation_id
        if x_callback_otp is not None:
            _header_params['X-Callback-OTP'] = x_callback_otp
        # process the form parameters
        # process the body parameter
        if tool_invocation_request is not None:
            _body_params = tool_invocation_request

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(['application/json'])
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ['bearerAuth']

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/tools/{toolkit_name}/{tool_name}/invoke',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
